### ISSUE TITLE
Unexpected Behavior Under Ubuntu 24.04

### ISSUE THREAD

**Issue by murabus** [dirtyhawk/stata-integration#9]
My official Stata installation (16.1) worked as it should under Ubuntu 22.04, file associations were correct and icons correctly represented the file types associated with Stata (.dta, .do, .gph, etc.). I did a fresh install for Ubuntu 24.04 and upon executing the stata-integration.bin, the file types were correctly associated. The icons for different types of files are missing. And when I open any of these files, a separate Stata instance opens and this has no icon associated with it (I have the Stata with the correct icon in the dock also). I was wondering if anybody else encountered these issues.

**Comment by dirtyhawk** [comment]
Hi @murabus , thanks for reaching out.

Indeed, I also encounter the same behavior on my machine. I didn't find the time yet to look into the issue, but will do!

**Comment by dirtyhawk** [comment]
For the record, there has been an [upstream discussion](https://gitlab.gnome.org/GNOME/nautilus/-/issues/2190) about that distinct behavior of the GNOME desktop environment. The result was an “expected behavior” tag upstream, that's why we needed a workaround (which is implemented since [release 1.0.0](https://github.com/dirtyhawk/stata-integration/releases/tag/v1.0)).
